import { useEffect, useRef, useState } from "react";
import { base44 } from "@/api/base44Client";
import { useToast } from "@/components/ui/use-toast";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";
import { RefreshCw, Upload, Link2, Database, Plus } from "lucide-react";
import { ingestFile, ingestUrl, ingestSqlPreset } from "@/core/ai/ragLayer";
import ChromaExplorer from "./ChromaExplorer";

export default function RagManager() {
  const { toast } = useToast(); const fileRef = useRef(null); const [kbs, setKbs] = useState([]); const [kbId, setKbId] = useState(""); const [modal, setModal] = useState(null); const [url, setUrl] = useState(""); const [sqlPreset, setSqlPreset] = useState(""); const [busy, setBusy] = useState(false);
  const load = async () => { try { const list = await base44.entities.KnowledgeBase.list("-created_date", 100); setKbs(list); if (!kbId && list[0]) setKbId(list[0].id); } catch (err) { toast({ title: "Knowledge Bases indisponibles", description: err.message, variant: "destructive" }); } };
  useEffect(() => { load(); }, []);
  const close = () => { if (!busy) setModal(null); };
  const upload = async () => { const file = fileRef.current?.files?.[0]; if (!file || !kbId) return; try { setBusy(true); const result = await ingestFile({ knowledgeBaseId: kbId, file }); toast({ title: "Document indexé", description: `${file.name} — ${result.chunks || 0} chunks.` }); setModal(null); } catch (err) { toast({ title: "Erreur d’indexation", description: err.response?.data?.message || err.message, variant: "destructive" }); } finally { setBusy(false); if (fileRef.current) fileRef.current.value = ""; } };
  const addUrl = async () => { if (!url.trim() || !kbId) return; try { setBusy(true); const result = await ingestUrl({ knowledgeBaseId: kbId, url: url.trim() }); toast({ title: "URL indexée", description: `${result.chunks || 0} chunks.` }); setUrl(""); setModal(null); } catch (err) { toast({ title: "Erreur URL", description: err.response?.data?.message || err.message, variant: "destructive" }); } finally { setBusy(false); } };
  const addSql = async () => { if (!sqlPreset.trim()) return; try { setBusy(true); const result = await ingestSqlPreset({ preset: sqlPreset.trim() }); toast({ title: "Source SQL indexée", description: `${result.indexed || 0} lignes.` }); setSqlPreset(""); setModal(null); } catch (err) { toast({ title: "Erreur SQL", description: err.response?.data?.message || err.message, variant: "destructive" }); } finally { setBusy(false); } };
  return <div className="space-y-6">
    <ChromaExplorer onKnowledgeBaseChange={setKbId} headerActions={<div className="flex gap-2 flex-wrap"><Select onValueChange={(value) => value && setModal(value)} disabled={busy || !kbId}><SelectTrigger className="w-44"><SelectValue placeholder="Ajouter une source" /></SelectTrigger><SelectContent><SelectItem value="upload"><span className="flex items-center gap-2"><Upload className="h-4 w-4" /> Importer un fichier</span></SelectItem><SelectItem value="url"><span className="flex items-center gap-2"><Link2 className="h-4 w-4" /> Indexer une URL</span></SelectItem><SelectItem value="sql"><span className="flex items-center gap-2"><Database className="h-4 w-4" /> Source SQL</span></SelectItem></SelectContent></Select><Button variant="outline" onClick={load} disabled={busy}><RefreshCw className="h-4 w-4 mr-2" /> Actualiser</Button></div>} />
    <Dialog open={Boolean(modal)} onOpenChange={(open) => !open && close()}><DialogContent className="sm:max-w-lg"><DialogHeader><DialogTitle>{modal === "upload" ? "Importer un document" : modal === "url" ? "Indexer une URL" : "Indexer une source SQL"}</DialogTitle><DialogDescription>{modal === "upload" ? "Le document sera découpé puis indexé dans la Knowledge Base active." : modal === "url" ? "Saisissez une URL publique." : "Utilisez un preset SQL autorisé."}</DialogDescription></DialogHeader>{modal === "upload" && <div className="space-y-2"><Label>Fichier</Label><Input ref={fileRef} type="file" accept=".pdf,.docx,.xlsx,.csv,.txt,.md,.text" /></div>}{modal === "url" && <div className="space-y-2"><Label>URL publique</Label><Input autoFocus value={url} onChange={(e) => setUrl(e.target.value)} placeholder="https://exemple.com/procedure" /></div>}{modal === "sql" && <div className="space-y-2"><Label>Preset SQL</Label><Input autoFocus value={sqlPreset} onChange={(e) => setSqlPreset(e.target.value)} placeholder="nom-du-preset" /></div>}<DialogFooter><Button variant="outline" onClick={close} disabled={busy}>Annuler</Button><Button onClick={modal === "upload" ? upload : modal === "url" ? addUrl : addSql} disabled={busy || (modal === "upload" ? false : !(modal === "url" ? url.trim() : sqlPreset.trim()))}>{busy ? "Traitement…" : <><Plus className="h-4 w-4 mr-1.5" /> Indexer</>}</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}
